# Generated by Django 4.2.3 on 2023-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ssummary',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(default='rate it'),
        ),
    ]
